/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
 /*\title ILLD_TC4D7_LK_ADS_ONEEYE_UART_ALLINONE
 * \abstract Demonstrate how to implement a data multiplexer, oscilloscope, and shell using the Infineon GUI Designer (OneEye) over the UART (USB) interface.
 * \description Demonstrate how to implement a data multiplexer, oscilloscope, and shell using the Infineon GUI Designer (OneEye) over the UART (USB) interface.
 *              
 *              This project showcases how to integrate multiple functionalities: data multiplexer, oscilloscope, and shell using the Infineon GUI Designer (OneEye) over the UART (USB) interface. After configuring the UART interface in OneEye, three key components are implemented:
 *              
 *              1. Data Multiplexer: This module routes multiple signal sources through the UART interface, allowing OneEye to visualize and monitor multiple data streams efficiently.
 *              
 *              2. Oscilloscope: Signal values are sampled and updated every millisecond, enabling real-time waveform visualization directly within the Infineon GUI Designer.
 *              
 *              3. Shell Interface: A shell parser is integrated to interpret command-line inputs and execute corresponding commands, such as info or help, providing a flexible way to interact with the system.
 *              
 *              By combining these components, the Infineon GUI Designer becomes a powerful interface for both monitoring and control through the USB UART connection.
 *
 * \name iLLD_TC4D7_LK_ADS_ONEEYE_UART_ALLINONE
 * \version V1.0.0
 * \board AURIX TC4D7 lite Kit, KIT_A3G_TC4D7_LITE, TC4D7XP_A-Step_MC_COM
 * \keywords OneEye, Oscilloscope, Shell, Multiplexer, UART
 * \documents see README.md
 * \lastUpdated 2025-11-12
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxWtu.h"
#include "ifx_oe_syncprotocol.h"
#include "oneeyeshell.h"
#include "oneeyeuart.h"
#include "oneeyetest.h"
#include "oneeyedatamultiplexer.h"
#include "oneeyeoscilloscope.h"
#include "oneeyesignalgenerator.h"

/******************************************************************************/
/*-----------------------------------Macros-----------------------------------*/
/******************************************************************************/


/** Timeout after which the BB protocol discards the frame */
#define BB_REMOTE_TIMEOUT (1000)

#define UPDATE_INTERVAL 10                                         /* Update interval in ms                       */

/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/

Ifx_Oe_SyncProtocol g_oneeyeBb;                     /* SyncProtocol driver                          */

/******************************************************************************/
/*-------------------------Function Implementations---------------------------*/
/******************************************************************************/

/*******************************************************************************
* This is the main function. It initializes the
* - UART
* - BB protocol
* - Shell interface
* - Oscilloscope
* - Data multiplexer
* and processes them inside the main loop.
*
*******************************************************************************/
void core0_main(void)
{
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxWtu_disableCpuWatchdog(IfxWtu_getCpuWatchdogPassword());
    IfxWtu_disableSystemWatchdog(IfxWtu_getSystemWatchdogPassword());

    /* Initialize the UART */
    OneEyeUart_init();

    /* Enable the global interrupts  */
    IfxCpu_enableInterrupts();

#if defined(ENABLE_BB_OSCILLOSCOPE) || defined(ENABLE_BB_MUX)
    /* Initialize signal generator */
    SignalGenerator_init();
#endif

#ifdef ENABLE_BB
    /* Initialize the BB protocol */
    Ifx_Oe_SyncProtocol_init(&g_oneeyeBb, BB_REMOTE_TIMEOUT, &g_OneEyeUart_uart.pipe);
#else
    /* Send Hello World to the UART */
    Ifx_Oe_StdIf_DPipe_print(&g_OneEyeUart_uart.pipe, "Hello world!" IFX_OE_ENDL);

#endif

#ifdef ENABLE_BB_SHELL
    /* Initialize the shell */
    OneEyeShell_init(&g_oneeyeBb);
#endif

#ifdef ENABLE_BB_OSCILLOSCOPE
    /* Initialize the oscilloscope */
    OneEyeOscilloscope_init(&g_oneeyeBb, UPDATE_INTERVAL);
#endif

#ifdef ENABLE_BB_MUX
    /* Initialize the data multiplexer */
    OneEyeDataMultiplexer_init(&g_oneeyeBb);
#endif

    /* background endless loop */
    Ifx_Oe_TickTime deadline = 0;

    while (1)
    {
#ifdef ENABLE_BB
        /* Update the sync protocol */
        Ifx_Oe_SyncProtocol_execute(&g_oneeyeBb);
#endif

#ifdef ENABLE_BB_SHELL
        /* Process the shell */
        OneEyeShell_process();
#endif

#ifdef ENABLE_BB_OSCILLOSCOPE
        /* Process the Oscilloscope */
        OneEyeOscilloscope_process();
#endif

#ifdef ENABLE_BB_MUX
        /* Process the data multiplexer */
        OneEyeDataMultiplexer_process();
#endif

        /* Update the signal generator and oscilloscope periodically */
        if (Ifx_Oe_Time_isDeadLine(deadline))
        {
            deadline = Ifx_Oe_Time_add(deadline, Ifx_Oe_Time_getTickForMilliseconds(UPDATE_INTERVAL));

#if defined(ENABLE_BB_OSCILLOSCOPE) || defined(ENABLE_BB_MUX)
            /* Update the signal generator */
            SignalGenerator_process();
#endif

#ifdef ENABLE_BB_OSCILLOSCOPE
            /* Update the oscilloscope */
            /* NOTE: In real application the OneEyeOscilloscope_sample() should may be called
             * from an interrupt to sample data synchronously to  the control loop for example
             */
            OneEyeOscilloscope_sample();
#endif
        }


#ifndef ENABLE_BB

            OneEyeTest_process();
#endif
    }
}
