/**
 * \file IfxGtm.h
 * \brief GTM  basic functionality
 * \ingroup IfxLld_Gtm
 *
 * \version iLLD_1_20_0
 * \copyright Copyright (c) 2024 Infineon Technologies AG. All rights reserved.
 *
 *
 *
 *                                 IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 *
 * \defgroup IfxLld_Gtm_Std_Basic_Functions Basic Functions
 * \ingroup IfxLld_Gtm_Std
 * \defgroup IfxLld_Gtm_Std_Enumerations Enumerations
 * \ingroup IfxLld_Gtm_Std
 */

#ifndef IFXGTM_H
#define IFXGTM_H 1

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/

#include "_Impl/IfxGtm_cfg.h"

/******************************************************************************/
/*--------------------------------Enumerations--------------------------------*/
/******************************************************************************/

/** \addtogroup IfxLld_Gtm_Std_Enumerations
 * \{ */
/** \brief Enum for GTM interrupt modes
 */
typedef enum
{
    IfxGtm_IrqMode_level       = 0,
    IfxGtm_IrqMode_pulse       = 1,
    IfxGtm_IrqMode_pulseNotify = 2,
    IfxGtm_IrqMode_singlePulse = 3
} IfxGtm_IrqMode;

/** \brief OCDS Suspend Control (OCDS.SUS)
 */
typedef enum
{
    IfxGtm_SuspendMode_none = 0,  /**< \brief No suspend */
    IfxGtm_SuspendMode_hard = 1,  /**< \brief Hard Suspend */
    IfxGtm_SuspendMode_soft = 2   /**< \brief Soft Suspend */
} IfxGtm_SuspendMode;

/** \} */

/** \addtogroup IfxLld_Gtm_Std_Basic_Functions
 * \{ */

/******************************************************************************/
/*-------------------------Inline Function Prototypes-------------------------*/
/******************************************************************************/

/**
 * \brief Returns the status of whether the GTM module is enabled or disabled.
 *
 * \param[in] gtm Pointer to the GTM module instance.
 *
 * \retval TRUE If the GTM module is enabled.
 * 		   FALSE If the GTM module is disabled.
 */
IFX_INLINE boolean IfxGtm_isEnabled(Ifx_GTM *gtm);

/**
 * \brief Checks if the GTM module is currently suspended.
 *
 * This function returns the current suspend state of the GTM module.
 *
 * \param[in] gtm Pointer to the GTM module instance.
 *
 * \retval TRUE Module is suspended.
 * 		   FALSE Module is not suspended.
 */
IFX_INLINE boolean IfxGtm_isModuleSuspended(Ifx_GTM *gtm);

/**
 * \brief Configures the GTM module to Hard/Soft suspend mode.
 * 
 * This function sets the suspend mode of the GTM module. The mode can be set to 
 * none, hard, or soft suspend. The function only works when the OCDS is enabled 
 * and the system is in Supervisor Mode. If OCDS is disabled, the suspend control 
 * will be ineffective.
 *
 * \param[inout] gtm  Pointer to the GTM module instance.
 * \param[in]    mode Suspend mode to be configured. 
 *					  Range: \ref IfxGtm_SuspendMode
 *
 * \retval None
 * 
 * \note The function will not work unless OCDS is enabled and the system is in 
 * Supervisor Mode. When OCDS is disabled, the OCS suspend control is ineffective.
 */
IFX_INLINE void IfxGtm_setSuspendMode(Ifx_GTM *gtm, IfxGtm_SuspendMode mode);

/******************************************************************************/
/*-------------------------Global Function Prototypes-------------------------*/
/******************************************************************************/

/**
 * \brief Disables the GTM module.
 *
 * \param[inout] gtm Pointer to the GTM module instance.
 *
 * \retval None
 */
IFX_EXTERN void IfxGtm_disable(Ifx_GTM *gtm);

/**
 * \brief Enables the GTM module
 *
 * \param[inout] gtm Pointer to the GTM module instance.
 * 
 * \retval None
 */
IFX_EXTERN void IfxGtm_enable(Ifx_GTM *gtm);

/** \} */

/******************************************************************************/
/*-------------------------Global Function Prototypes-------------------------*/
/******************************************************************************/

/**
 * \brief Retrieves the current frequency of the GTM system clock.
 *
 * This function returns the frequency of the GTM system clock (SYSCLK) in Hz.
 * The GTM system clock is a critical clock source for various timing operations
 * within the system.
 *
 * \retval float32 The current frequency of the GTM system clock in Hz.
 */
IFX_EXTERN float32 IfxGtm_getSysClkFrequency(void);

/**
 * \brief Returns the cluster frequency of the GTM cluster.
 * If the cluster is disabled, the function returns 0 as the frequency.
 *
 * \param[in] gtm Pointer to the GTM module instance.
 * \param[in] cluster Index of the cluster. Range: \ref IfxGtm_Cluster
 *
 * \retval float32 Cluster frequency in Hz, or 0 if the cluster is disabled.
 */
IFX_EXTERN float32 IfxGtm_getClusterFrequency(Ifx_GTM *gtm, IfxGtm_Cluster cluster);

/******************************************************************************/
/*---------------------Inline Function Implementations------------------------*/
/******************************************************************************/

IFX_INLINE boolean IfxGtm_isEnabled(Ifx_GTM *gtm)
{
    return gtm->CLC.B.DISS == 0;
}


IFX_INLINE boolean IfxGtm_isModuleSuspended(Ifx_GTM *gtm)
{
    Ifx_GTM_OCDS_OCS ocs;

    /* read the status */
    ocs.U = gtm->OCDS.OCS.U;

    /* return the status */
    return ocs.B.SUSSTA;
}


IFX_INLINE void IfxGtm_setSuspendMode(Ifx_GTM *gtm, IfxGtm_SuspendMode mode)
{
    Ifx_GTM_OCDS_OCS ocs;

    /* remove protection and configure the suspend mode. */
    ocs.B.SUS_P     = 1;
    ocs.B.SUS       = mode;

    gtm->OCDS.OCS.U = ocs.U;
}


#endif /* IFXGTM_H */
