/**********************************************************************************************************************
 * \file Watchdog.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Watchdog.h"
#include "IfxWtu.h"
#include "IfxCpu.h"

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/* Function to configure the port pins for the push button and the LEDs */
void initGPIOs(void)
{
    /* Setup the port pins connected to the LEDs to general output mode push-pull. */
    IfxPort_setPinMode(LED1, IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinMode(LED2, IfxPort_Mode_outputPushPullGeneral);

    IfxPort_setPinHigh(LED1);
    IfxPort_setPinHigh(LED2);

    /* Setup the port pin connected to the push button to input mode. This function can be used to initialize any
     * port to input mode by just specifying the port number as illustrated.
     */
    IfxPort_setPinMode(BUTTON, IfxPort_Mode_inputPullUp);
}

/* Function to check the state of the button */
uint8 isButtonPressed(void)
{
    if(IfxPort_getPinState(BUTTON) == 0)
    {
        return TRUE;                                        /* Return TRUE if the button is pressed                 */
    }
    else
    {
        return FALSE;                                       /* Return FALSE elsewhere                               */
    }
}

/* Function to configure the CPU0 Watchdog */
void initWatchdog(uint16 reloadValue)
{
    IfxWtu_Config conf;

    /* Set default configurations */
    IfxWtu_initConfig(&conf);

    conf.reload = reloadValue;                              /* Set the reload value of the Watchdog                 */
#if AUTOMATIC_PASSWORD_SEQUENCING==1
    /* Support of automatic password sequencing */
    conf.enableAutomaticPasswordChange=TRUE;
#endif
    IfxWtu_initCpuWatchdog(&MODULE_WTU.WDTCPU[0], &conf);   /* Initialize the Watchdog with the given configuration */
}

uint8 IfxWtu_getCpuWatchdogTim(void)
{
    Ifx_WTU *wtu = &MODULE_WTU;
    return wtu->WDTCPU[IfxCpu_getCoreIndex()].STAT.B.TIM;
}
