/**
 * \file IfxAudio_Mixer.h
 * \brief AUDIO MIXER details
 * \ingroup IfxLld_Audio
 *
 * \version iLLD-TC4-v2.4.0
 * \copyright Copyright (c) 2025 Infineon Technologies AG. All rights reserved.
 *
 *
 *
 *                                 IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 *
 * \defgroup IfxLld_Audio_Mixer MIXER
 * \ingroup IfxLld_Audio
 * \defgroup IfxLld_Audio_Mixer_Enum Enumerations
 * \ingroup IfxLld_Audio_Mixer
 * \defgroup IfxLld_Audio_Mixer_Structures Data Structures
 * \ingroup IfxLld_Audio_Mixer
 * \defgroup IfxLld_Audio_Mixer_Functions Module Interface Functions for Audio
 * \ingroup IfxLld_Audio_Mixer
 */

#ifndef IFXAUDIO_MIXER_H
#define IFXAUDIO_MIXER_H 1

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/

#include "Audio/Std/IfxAudio.h"
#include "Audio/Audio/IfxAudio_Audio.h"

/******************************************************************************/
/*--------------------------------Enumerations--------------------------------*/
/******************************************************************************/

/** \addtogroup IfxLld_Audio_Mixer_Enum
 * \{ */
/** \brief Specifies selection of the channel's 24-bit PCM data from the source FIFO data[31:0]. Refer MIXER_SRCi_CTL.CH0_SEL
 */
typedef enum
{
    IfxAudio_Mixer_PcmDataSelect_dataLow  = 0,  /**< \brief 0.5 (down sampling by 2x) */
    IfxAudio_Mixer_PcmDataSelect_dataHigh = 1,  /**< \brief 1 (Same as input. No re sampling.) */
    IfxAudio_Mixer_PcmDataSelect_const_0  = 2   /**< \brief 2 (up sampling by 2x) */
} IfxAudio_Mixer_PcmDataSelect;

/** \brief Sample Frequency Scale Ratio. Refer MIXER_SRCi_CTL.FS_RATIO
 */
typedef enum
{
    IfxAudio_Mixer_SampleFrequencyScaleRatio_0p5              = 0, /**< \brief 0.5 (down sampling by 2x) */
    IfxAudio_Mixer_SampleFrequencyScaleRatio_1                = 1, /**< \brief 1 (Same as input. No re sampling.) */
    IfxAudio_Mixer_SampleFrequencyScaleRatio_2                = 2, /**< \brief 2 (up sampling by 2x) */
    IfxAudio_Mixer_SampleFrequencyScaleRatio_3                = 3, /**< \brief 3 (up sampling by 3x) */
    IfxAudio_Mixer_SampleFrequencyScaleRatio_4                = 4, /**< \brief 4 (up sampling by 4x) */
    IfxAudio_Mixer_SampleFrequencyScaleRatio_6                = 5, /**< \brief 6 (up sampling by 6x) */
    IfxAudio_Mixer_SampleFrequencyScaleRatio_8                = 6, /**< \brief 8 (up sampling by 8x) */
    IfxAudio_Mixer_SampleFrequencyScaleRatio_12               = 7, /**< \brief 12 (up sampling by 12x) */
    IfxAudio_Mixer_SampleFrequencyScaleRatio_44p1KHz_to_48KHz = 8  /**< \brief 44.1KHz to 48KHz (up sampling by 160/147) */
} IfxAudio_Mixer_SampleFrequencyScaleRatio;

/** \} */

/******************************************************************************/
/*-----------------------------Data Structures--------------------------------*/
/******************************************************************************/

/** \addtogroup IfxLld_Audio_Mixer_Structures
 * \{ */
/** \brief Configuration Structure of the Mixer Destination Fifo
 */
typedef struct
{
    uint8          gainControlCode;       /**< \brief Mixer Destination Fifo gain control. Default is 115 for no change. Range is 0 (digital mute) to 127. Refer to MIXER_DST_GAIN_CTL.CODE */
    uint8          triggerLevel;          /**< \brief Mixer Destination fifo interrupt trigger level. When the source FIFO has less entries than the number of this field, a transmitter trigger event is generated. Range is 0 to 127. */
    IfxAudio_DmaCh dmaChannelIndex;       /**< \brief Select the Dma channel */
    uint32         interruptMask;         /**< \brief Mixer Destination Fifo interrupt mask */
    boolean        wordAlign;             /**< \brief Mixer destination word alignment, FALSE: Left Align, TRUE: Right Align . */
    boolean        wordSignExtend;        /**< \brief Mixer destination word sign extension, FALSE: Zero extension, TRUE: Sign extension. */
} IfxAudio_Mixer_DstFifoConfig;

/** \brief Configuration Structure of the Mixer Source Fifo
 */
typedef struct
{
    IfxAudio_Mixer_SampleFrequencyScaleRatio samplingFrequencyScaleRatio;       /**< \brief Select the sampling frequency scale ratio at the Source Fifo */
    IfxAudio_Mixer_PcmDataSelect             dataSelect;                        /**< \brief Select the 24 bit PCM data from the Source Fifo data */
    uint8                                    gainControlCode;                   /**< \brief Mixer source fifo gain control. Default is 115 for no change. Range is 0 (digital mute) to 127. Refer to MIXER_SRCi_GAIN_CTL.CODE */
    uint8                                    triggerLevel;                      /**< \brief Mixer source fifo interrupt trigger level. When the source FIFO has less entries than the number of this field, a transmitter trigger event is generated. Range is 0 to 127. */
    IfxAudio_DmaCh                           dmaChannelIndex;                   /**< \brief Select the Dma channel */
    uint32                                   interruptMask;                     /**< \brief Mixer Source Fifo interrupt mask */
} IfxAudio_Mixer_SrcFifoConfig;

/** \} */

/** \addtogroup IfxLld_Audio_Mixer_Functions
 * \{ */

/******************************************************************************/
/*-------------------------Global Function Prototypes-------------------------*/
/******************************************************************************/

/** \brief Configure the DMA channel for the given Mixer Source Fifo
 * \param audio Specifies the module handle
 * \param mixerSrcFifoIndex Specifies the index of the Mixer Source Fifo
 * \param dmaChannelIndex Specifies the Dma Channel used
 * \return None
 */
IFX_EXTERN void IfxAudio_Mixer_srcFifoDmaChannelSelect(IfxAudio_Audio *audio, IfxAudio_MixerSrcFifoIndex mixerSrcFifoIndex, IfxAudio_DmaCh dmaChannelIndex);

/** \brief Returns the Masked Interrupt Status for the given Mixer Source Fifo
 * \param audio Specifies the module handle
 * \param mixerSrcFifoIndex Specifies the index of the Mixer Source Fifo
 * \return value in masked interrupt register
 */
IFX_EXTERN uint32 IfxAudio_Mixer_getSrcFifoMaskedInterruptStatus(IfxAudio_Audio *audio, IfxAudio_MixerSrcFifoIndex mixerSrcFifoIndex);

/** \brief Writes one data word into the given Mixer Source Fifo
 * \param audio Specifies the module handle
 * \param mixerSrcFifoIndex Specifies the index of the Mixer Source Fifo
 * \param data data word to be written to FIFO
 * \return None
 */
IFX_EXTERN void IfxAudio_Mixer_srcFifoWrite(IfxAudio_Audio *audio, IfxAudio_MixerSrcFifoIndex mixerSrcFifoIndex, uint32 data);

/** \brief Returns the number of used entries in Mixer Source Fifo
 * \param audio Specifies the module handle
 * \param mixerSrcFifoIndex Specifies the index of the Mixer Source Fifo
 * \return Number of used/occupied entries in the source FIFO. The field value is in the range [0, 128]. When "0", the FIFO is empty. When "128", the FIFO is full.
 */
IFX_EXTERN uint32 IfxAudio_Mixer_getSrcFifoUsedStatus(IfxAudio_Audio *audio, IfxAudio_MixerSrcFifoIndex mixerSrcFifoIndex);

/** \brief Mute the given Mixer Source Fifo
 * \param audio Specifies the module handle
 * \param mixerSrcFifoIndex Specifies the index of the Mixer Source Fifo
 * \return None
 */
IFX_EXTERN void IfxAudio_Mixer_muteSrcFifo(IfxAudio_Audio *audio, IfxAudio_MixerSrcFifoIndex mixerSrcFifoIndex);

/** \brief Unmute the given Mixer Source Fifo
 * \param audio Specifies the module handle
 * \param mixerSrcFifoIndex Specifies the index of the Mixer Source Fifo
 * \return None
 */
IFX_EXTERN void IfxAudio_Mixer_unMuteSrcFifo(IfxAudio_Audio *audio, IfxAudio_MixerSrcFifoIndex mixerSrcFifoIndex);

/** \brief Activate the given Mixer Source Fifo
 * \param audio Specifies the module handle
 * \param mixerSrcFifoIndex Specifies the index of the Mixer Source Fifo
 * \return None
 */
IFX_EXTERN void IfxAudio_Mixer_activateSrcFifo(IfxAudio_Audio *audio, IfxAudio_MixerSrcFifoIndex mixerSrcFifoIndex);

/** \brief Deactivate the given Mixer Source Fifo
 * \param audio Specifies the module handle
 * \param mixerSrcFifoIndex Specifies the index of the Mixer Source Fifo
 * \return None
 */
IFX_EXTERN void IfxAudio_Mixer_deactivateSrcFifo(IfxAudio_Audio *audio, IfxAudio_MixerSrcFifoIndex mixerSrcFifoIndex);

/** \brief Configure gain value of the given Mixer Source Fifo
 * \param audio Specifies the module handle
 * \param mixerSrcFifoIndex Specifies the index of the Mixer Source Fifo
 * \param gainControlValue Gain Control value. Gain code in the range [0, 127]. Each gain code increment represents 1dB. Gain code value "0" represents digital mute. Gain code "127" represents a maximum amplification of 12 dB. Refer to MIXER_SRCi_GAIN_CTL.CODE
 * \return None
 */
IFX_EXTERN void IfxAudio_Mixer_setSrcFifoGainControl(IfxAudio_Audio *audio, IfxAudio_MixerSrcFifoIndex mixerSrcFifoIndex, uint8 gainControlValue);

/** \brief Activate Fade In mechanism in the given Mixer Source Fifo
 * \param audio Specifies the module handle
 * \param mixerSrcFifoIndex Specifies the index of the Mixer Source Fifo
 * \param pace Pace value for each Fade In step
 * \return None
 */
IFX_EXTERN void IfxAudio_Mixer_enableSrcFifoFadeIn(IfxAudio_Audio *audio, IfxAudio_MixerSrcFifoIndex mixerSrcFifoIndex, uint16 pace);

/** \brief Activate Fade Out mechanism in the given Mixer Source Fifo
 * \param audio Specifies the module handle
 * \param mixerSrcFifoIndex Specifies the index of the Mixer Source Fifo
 * \param pace Pace value for each Fade Out step
 * \param enableAutoDeactivate enable or disable auto deactivate feature after completion of Fade out. TRUE: Source FIFO is deactivated by H/w, FALSE: Source FIFO is not deactivated by H/w
 * \return None
 */
IFX_EXTERN void IfxAudio_Mixer_enableSrcFifoFadeOut(IfxAudio_Audio *audio, IfxAudio_MixerSrcFifoIndex mixerSrcFifoIndex, uint16 pace, boolean enableAutoDeactivate);

/** \brief Set the fade control value in the given Mixer Source Fifo. Note: SW is typically required to reprogram the CODE field in between successive "fade in" operations or in between successive "fade out" operations.
 * \param audio Specifies the module handle
 * \param mixerSrcFifoIndex Specifies the index of the Mixer Source Fifo
 * \param fadeControlValue Fade control value. Refer to MIXER_SRCi_FADE_CTL.CODE
 * \return None
 */
IFX_EXTERN void IfxAudio_Mixer_setSrcFifoFadeControl(IfxAudio_Audio *audio, IfxAudio_MixerSrcFifoIndex mixerSrcFifoIndex, uint8 fadeControlValue);

/** \brief Enable the Mixer Source Fifo
 * \param audio Specifies the module handle
 * \param mixerSrcFifoIndex Specifies the index of the Mixer Source Fifo
 * \return None
 */
IFX_EXTERN void IfxAudio_Mixer_enableSrcFifo(IfxAudio_Audio *audio, IfxAudio_MixerSrcFifoIndex mixerSrcFifoIndex);

/** \brief Disable the Mixer Source Fifo
 * \param audio Specifies the module handle
 * \param mixerSrcFifoIndex Specifies the index of the Mixer Source Fifo
 * \return None
 */
IFX_EXTERN void IfxAudio_Mixer_disableSrcFifo(IfxAudio_Audio *audio, IfxAudio_MixerSrcFifoIndex mixerSrcFifoIndex);

/** \brief Configure the DMA channel for the given Mixer Destination Fifo
 * \param audio Specifies the module handle
 * \param dmaChannelIndex Specifies the Dma Channel used
 * \return None
 */
IFX_EXTERN void IfxAudio_Mixer_dstFifoDmaChannelSelect(IfxAudio_Audio *audio, IfxAudio_DmaCh dmaChannelIndex);

/** \brief Returns the Masked Interrupt Status for the given Mixer Destination Fifo
 * \param audio Specifies the module handle
 * \return value in masked interrupt register
 */
IFX_EXTERN uint32 IfxAudio_Mixer_getDstFifoMaskedInterruptStatus(IfxAudio_Audio *audio);

/** \brief Reads one data word from the Mixer Destination Fifo
 * \param audio Specifies the module handle
 * \return data word read from FIFO
 */
IFX_EXTERN uint32 IfxAudio_Mixer_dstFifoRead(IfxAudio_Audio *audio);

/** \brief Silently Reads one data word from the Mixer Destination Fifo
 * \param audio Specifies the module handle
 * \return data word silently read from FIFO
 */
IFX_EXTERN uint32 IfxAudio_Mixer_dstFifoSilentRead(IfxAudio_Audio *audio);

/** \brief Returns the number of used entries in Mixer Destination Fifo
 * \param audio Specifies the module handle
 * \return Number of used/occupied entries in the destination FIFO. The field value is in the range [0, 64]. When "0", the FIFO is empty. When "64", the FIFO is full.
 */
IFX_EXTERN uint32 IfxAudio_Mixer_getDstFifoUsedStatus(IfxAudio_Audio *audio);

/** \brief Mute the Mixer Destination Fifo
 * \param audio Specifies the module handle
 * \return None
 */
IFX_EXTERN void IfxAudio_Mixer_muteDstFifo(IfxAudio_Audio *audio);

/** \brief Unmute the Mixer Destination Fifo
 * \param audio Specifies the module handle
 * \return None
 */
IFX_EXTERN void IfxAudio_Mixer_unMuteDstFifo(IfxAudio_Audio *audio);

/** \brief Activate the Mixer Destination Fifo
 * \param audio Specifies the module handle
 * \return None
 */
IFX_EXTERN void IfxAudio_Mixer_activateDstFifo(IfxAudio_Audio *audio);

/** \brief De-activate the Mixer Destination Fifo
 * \param audio Specifies the module handle
 * \return None
 */
IFX_EXTERN void IfxAudio_Mixer_deactivateDstFifo(IfxAudio_Audio *audio);

/** \brief Configure gain value of Mixer Destination Fifo
 * \param audio Specifies the module handle
 * \param gainControlValue Gain Control value. Gain code in the range [0, 127]. Each gain code increment represents 1dB. Gain code value "0" represents digital mute. Gain code "127" represents a maximum amplification of 12 dB. Refer to MIXER_DST_GAIN_CTL.CODE
 * \return None
 */
IFX_EXTERN void IfxAudio_Mixer_setDstFifoGainControl(IfxAudio_Audio *audio, uint8 gainControlValue);

/** \brief Activate Fade In mechanism in Mixer Destination Fifo
 * \param audio Specifies the module handle
 * \param pace Pace value for each Fade In step
 * \return None
 */
IFX_EXTERN void IfxAudio_Mixer_enableDstFifoFadeIn(IfxAudio_Audio *audio, uint16 pace);

/** \brief Activate Fade Out mechanism in Mixer Destination Fifo
 * \param audio Specifies the module handle
 * \param pace Pace value for each Fade In step
 * \param enableAutoDeactivate enable or disable auto deactivate feature after completion of Fade out. TRUE: Destination FIFO is deactivated by H/w, FALSE: Destination FIFO is not deactivated by H/w
 * \return None
 */
IFX_EXTERN void IfxAudio_Mixer_enableDstFifoFadeOut(IfxAudio_Audio *audio, uint16 pace, boolean enableAutoDeactivate);

/** \brief Set the fade control value in Mixer Destination Fifo. Note: SW is typically required to reprogram the CODE field in between successive ""fade in"" operations or in between successive ""fade out"" operations."
 * \param audio Specifies the module handle
 * \param fadeControlValue Fade control value. Refer to MIXER_DST_FADE_CTL.CODE
 * \return None
 */
IFX_EXTERN void IfxAudio_Mixer_setDstFifoFadeControl(IfxAudio_Audio *audio, uint8 fadeControlValue);

/** \brief Enable the Mixer Destination Fifo
 * \param audio Specifies the module handle
 * \return None
 */
IFX_EXTERN void IfxAudio_Mixer_enableDstFifo(IfxAudio_Audio *audio);

/** \brief Disable the Mixer Destination Fifo
 * \param audio Specifies the module handle
 * \return None
 */
IFX_EXTERN void IfxAudio_Mixer_disableDstFifo(IfxAudio_Audio *audio);

/** \brief Configure the Mixer Source Fifo
 * \param audio Specifies the module handle
 * \param mixerSrcFifoIndex Specifies the index of the Mixer Source Fifo
 * \param config Specifies the pointer to Mixer Source Fifo Configuration structure
 * \return None
 */
IFX_EXTERN void IfxAudio_Mixer_configureSrcFifo(IfxAudio_Audio *audio, IfxAudio_MixerSrcFifoIndex mixerSrcFifoIndex, IfxAudio_Mixer_SrcFifoConfig *config);

/** \brief Configure the Mixer Destination Fifo
 * \param audio Specifies the module handle
 * \param config Specifies the pointer to Mixer Destination Fifo Configuration structure
 * \return None
 */
IFX_EXTERN void IfxAudio_Mixer_configureDstFifo(IfxAudio_Audio *audio, IfxAudio_Mixer_DstFifoConfig *config);

/** \} */

#endif /* IFXAUDIO_MIXER_H */
