/**
 * \file IfxVmt_cfg_TC4Zx.c
 * \brief Vmt on-chip implementation data
 *
 * \version iLLD-TC4-v2.4.0
 * \copyright Copyright (c) 2025 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such
 * terms of use are agreed, use of this file is subject to following:
 *
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or
 * organization obtaining a copy of the software and accompanying
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/

#include "Ifx_Cfg.h"
#if defined (__TASKING__)
#pragma warning 508		/* To suppress empty file warning */
#endif
#if defined (__ghs__)
#pragma diag_suppress 96		/* To suppress empty file warning */
#endif

#if defined(DEVICE_TC4ZX)

#include "IfxVmt_cfg.h"
#include "Vmt/Std/IfxVmt.h"

/******************************************************************************/
/*-----------------------Exported Variables/Constants-------------------------*/
/******************************************************************************/

IFX_CONST IfxVmt_SramItem IfxVmt_sramTable[IFXVMT_NUM_MBIST_TABLE_ITEMS] = {
    {2 * 4, 16,  6, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu0Dspr0 */
    {2 * 1, 25,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu0Dtag */
    {1 * 2, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu0Pspr */
    {2 * 1, 22,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu0Ptag */
    {2 * 1, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu0DlmuStby */
    {2 * 4, 16,  6, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu1Dspr0 */
    {2 * 1, 25,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu1Dtag */
    {1 * 2, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu1Pspr */
    {2 * 1, 22,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu1Ptag */
    {2 * 1, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu1DlmuStby */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {1 * 4, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_dma0 */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {2 * 1, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_lmu0 */
    {2 * 1, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_lmu1 */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {1 * 1, 16,  6, 0, 1}, /**< \brief IfxVmt_MbistSel_cssKeyattr */
    {1 * 4, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_cssKeystore */
    {1 * 4, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_cssFifo0 */
    {1 * 4, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_cssFifo1 */
    {1 * 4, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_cssContext */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {2 * 4, 16,  6, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu2Dspr */
    {2 * 1, 25,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu2Dtag */
    {1 * 2, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu2Pspr */
    {2 * 1, 22,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu2Ptag */
    {2 * 1, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu2Dlmu */
    {2 * 4, 16,  6, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu3Dspr */
    {2 * 1, 25,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu3Dtag */
    {1 * 2, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu3Pspr */
    {2 * 1, 22,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu3Ptag */
    {2 * 1, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu3Dlmu */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {2 * 1, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_lmu2 */
    {2 * 1, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_lmu3 */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {1 * 4, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_dma1 */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {1 * 2, 128, 0, 0, 1}, /**< \brief IfxVmt_MbistSel_mcds4pTbuf */
    {1 * 4, 32,  0, 0, 1}, /**< \brief IfxVmt_MbistSel_mcds4pLut */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {1 * 1, 32,  0, 0, 1}, /**< \brief IfxVmt_MbistSel_audioTdm */
    {1 * 1, 32,  0, 0, 1}, /**< \brief IfxVmt_MbistSel_audioMixerIn */
    {1 * 1, 32,  0, 0, 1}, /**< \brief IfxVmt_MbistSel_audioMixerOut */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {4 * 1, 8,   0, 0, 1}, /**< \brief IfxVmt_MbistSel_scrXraml */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {2 * 4, 16,  6, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu4Dspr */
    {2 * 1, 25,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu4Dtag */
    {1 * 2, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu4Pspr */
    {2 * 1, 22,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu4Ptag */
    {2 * 1, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu4Dlmu */
    {2 * 4, 16,  6, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu5Dspr */
    {2 * 1, 25,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu5Dtag */
    {1 * 2, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu5Pspr */
    {2 * 1, 22,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu5Ptag */
    {2 * 1, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_cpu5Dlmu */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {2 * 1, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_lmu4 */
    {2 * 1, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_lmu5 */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {1 * 2, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_eray1Obf */
    {1 * 4, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_eray1IbfTbf */
    {1 * 1, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_eray1Mbf */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {1 * 2, 128, 0, 0, 1}, /**< \brief IfxVmt_MbistSel_mcds2pTbuf */
    {1 * 2, 32,  0, 0, 1}, /**< \brief IfxVmt_MbistSel_mcds2pLut */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {2 * 4, 16,  6, 0, 1}, /**< \brief IfxVmt_MbistSel_csrmDspr */
    {2 * 1, 25,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_csrmDtag */
    {1 * 2, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_csrmPspr */
    {2 * 1, 22,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_csrmPtag */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {1 * 2, 68,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_mod8 */
    {1 * 4, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_ethermacAxi */
    {1 * 1, 72,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_ethermacDmi */
    {1 * 1, 39,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_ethermac0Gcl */
    {1 * 1, 39,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_ethermac1Gcl */
    {1 * 4, 76,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_ethermacRxEven */
    {1 * 4, 76,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_ethermacRxOdd */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {1 * 2, 16,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_hsphyPcs0 */
    {1 * 2, 16,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_hsphyPcs1 */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {1 * 1, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_canxl */
    {1 * 1, 64,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_dreRam */
    {1 * 1, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_mcan0 */
    {1 * 1, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_mcan1 */
    {1 * 1, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_mcan2 */
    {1 * 1, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_mcan3 */
    {1 * 1, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_mcan4 */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {1 * 2, 35,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_leth0Port0TxFifo */
    {1 * 2, 35,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_leth0Port1TxFifo */
    {1 * 2, 35,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_leth0Port2TxFifo */
    {1 * 2, 35,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_leth0Port3TxFifo */
    {1 * 2, 35,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_leth0Port0RxFifo */
    {1 * 2, 35,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_leth0Port1RxFifo */
    {1 * 2, 35,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_leth0Port2RxFifo */
    {1 * 2, 35,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_leth0Port3RxFifo */
    {1 * 2, 48,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_leth0Port0RxParser */
    {1 * 2, 48,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_leth0Port1RxParser */
    {1 * 2, 48,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_leth0Port2RxParser */
    {1 * 2, 48,  8, 0, 1}, /**< \brief IfxVmt_MbistSel_leth0Port3RxParser */
    {1 * 1, 29,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_leth0Port0Gcl */
    {1 * 1, 29,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_leth0Port1Gcl */
    {1 * 1, 29,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_leth0Port2Gcl */
    {1 * 1, 29,  7, 0, 1}, /**< \brief IfxVmt_MbistSel_leth0Port3Gcl */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {1 * 1, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_sdmmc */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {1 * 2, 39,  0, 0, 0}, /**< \brief IfxVmt_MbistSel_cdsp0Data */
    {2 * 2, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_cdsp0Prog */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {1 * 1, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_psi5 */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {1 * 2, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_eray0Obf */
    {1 * 4, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_eray0IbfTbf */
    {1 * 1, 32,  7, 1, 4}, /**< \brief IfxVmt_MbistSel_eray0Mbf */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
    {0 * 0, 0,   0, 0, 0}, /**< \brief IfxVmt_MbistSel_none */
};

#endif /* #if defined DEVICE_TC4ZX */

#if defined (_TASKING_) || defined (_ghs_)
#pragma restore
#endif
