/**********************************************************************************************************************
 * \file serialio.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

#include "IfxAsclin_bf.h"
#include "IfxScuWdt.h"
#include "IfxCpu.h"
#include <TLF35584.h>
#include <serialio.h>

/*********************************************************************************************************************/
/*-----------------------------------------------------globaleV------------------------------------------------------*/
/*********************************************************************************************************************/
#define UART_BAUDRATE           19200
#define UART_RX                 IfxAsclin0_RXA_P14_1_IN
#define UART_TX                 IfxAsclin0_TX_P14_0_OUT
#define INTPRIO_ASCLIN0_RX      18                                          /* Priority of the ISR                  */
#define ASC_RX_BUFFER_SIZE      64                                          /* Definition of the buffer size        */
#define ASC_TX_BUFFER_SIZE      64
uint8 g_ascRxBuffer[ASC_RX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];
IfxAsclin_Asc ascHandle;
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

IFX_INTERRUPT(asclin0_Rx_ISR, 0, INTPRIO_ASCLIN0_RX);

void asclin0_Rx_ISR(void)
{
    IfxAsclin_Asc_isrReceive(&ascHandle);
    g_mode = stateTransition;

}

void SERIALIO_Init (void)
{
    /* Initialize an instance of IfxAsclin_Asc_Config with default values */
    IfxAsclin_Asc_Config ascConfig;
    IfxAsclin_Asc_initModuleConfig(&ascConfig, &MODULE_ASCLIN0);

    ascConfig.baudrate.baudrate = (float32)UART_BAUDRATE;                            /* Set the desired baud rate         */

    /* ISR priorities and interrupt target */
    ascConfig.interrupt.rxPriority = INTPRIO_ASCLIN0_RX;
    ascConfig.interrupt.typeOfService = IfxCpu_Irq_getTos(IfxCpu_getCoreIndex());

    /* FIFO configuration */
    ascConfig.rxBuffer = &g_ascRxBuffer;
    ascConfig.rxBufferSize = ASC_RX_BUFFER_SIZE;

    /* Pin configuration */
    const IfxAsclin_Asc_Pins pins = {
        NULL_PTR, IfxPort_InputMode_pullUp,                                     /* CTS pin not used                  */
        &UART_RX, IfxPort_InputMode_pullUp,                              /* RX pin                            */
        NULL_PTR, IfxPort_OutputMode_pushPull,                                  /* RTS pin not used                  */
        &UART_TX, IfxPort_OutputMode_pushPull,                           /* TX pin                            */
        IfxPort_PadDriver_cmosAutomotiveSpeed1};
    ascConfig.pins = &pins;

    /* Initialize module with above parameters */
    IfxAsclin_Asc_initModule(&ascHandle, &ascConfig);

    /* Set the Transmit FIFO Level Flag (TFL) via the FLAGSSET register to start the transmission */
    MODULE_ASCLIN0.FLAGSSET.B.TFLS = 1;
    g_mode = noStateTransition;
}

#ifdef __TASKING__

/* Retarget for Tasking compiler */
void _io_putc (char character)
{
    while (IfxAsclin_getTxFifoFillLevelFlagStatus(&MODULE_ASCLIN0) != TRUE)
    {}

    IfxAsclin_clearTxFifoFillLevelFlag(&MODULE_ASCLIN0);

    /* Send the character */
    IfxAsclin_writeTxData(&MODULE_ASCLIN0, character);
}

#endif /* __TASKING__ */
