################################################################################
# Automatically-generated file. Do not edit!
################################################################################

OBJ_SRCS := 
SRC_SRCS := 
C_SRCS := 
O_SRCS := 
EXECUTABLES := 
OBJS := 
SECONDARY_SIZE := 
COMPILED_SRCS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Configurations/MCU \
. \
Libraries/Infra/Platform/Tricore/Compilers \
Libraries/Service/CpuGeneric/If \
Libraries/Service/CpuGeneric/StdIf \
Libraries/Service/CpuGeneric/SysSe/Bsp \
Libraries/Service/CpuGeneric/SysSe/Comm \
Libraries/Service/CpuGeneric/SysSe/General \
Libraries/Service/CpuGeneric/SysSe/Math \
Libraries/Service/CpuGeneric/SysSe/Time \
Libraries/iLLD/TC29B/Tricore/Asclin/Asc \
Libraries/iLLD/TC29B/Tricore/Asclin/Lin \
Libraries/iLLD/TC29B/Tricore/Asclin/Spi \
Libraries/iLLD/TC29B/Tricore/Asclin/Std \
Libraries/iLLD/TC29B/Tricore/Ccu6/Icu \
Libraries/iLLD/TC29B/Tricore/Ccu6/PwmBc \
Libraries/iLLD/TC29B/Tricore/Ccu6/PwmHl \
Libraries/iLLD/TC29B/Tricore/Ccu6/Std \
Libraries/iLLD/TC29B/Tricore/Ccu6/TPwm \
Libraries/iLLD/TC29B/Tricore/Ccu6/Timer \
Libraries/iLLD/TC29B/Tricore/Ccu6/TimerWithTrigger \
Libraries/iLLD/TC29B/Tricore/Cif/Cam \
Libraries/iLLD/TC29B/Tricore/Cif/Std \
Libraries/iLLD/TC29B/Tricore/Cpu/CStart \
Libraries/iLLD/TC29B/Tricore/Cpu/Irq \
Libraries/iLLD/TC29B/Tricore/Cpu/Std \
Libraries/iLLD/TC29B/Tricore/Cpu/Trap \
Libraries/iLLD/TC29B/Tricore/Dma/Dma \
Libraries/iLLD/TC29B/Tricore/Dma/Std \
Libraries/iLLD/TC29B/Tricore/Dsadc/Dsadc \
Libraries/iLLD/TC29B/Tricore/Dsadc/Rdc \
Libraries/iLLD/TC29B/Tricore/Dsadc/Std \
Libraries/iLLD/TC29B/Tricore/Dts/Dts \
Libraries/iLLD/TC29B/Tricore/Dts/Std \
Libraries/iLLD/TC29B/Tricore/Ebu/BFlashSpansion \
Libraries/iLLD/TC29B/Tricore/Ebu/BFlashSt \
Libraries/iLLD/TC29B/Tricore/Ebu/Dram \
Libraries/iLLD/TC29B/Tricore/Ebu/Sram \
Libraries/iLLD/TC29B/Tricore/Ebu/Std \
Libraries/iLLD/TC29B/Tricore/Emem/Std \
Libraries/iLLD/TC29B/Tricore/Eray/Eray \
Libraries/iLLD/TC29B/Tricore/Eray/Std \
Libraries/iLLD/TC29B/Tricore/Eth/Phy_Pef7071 \
Libraries/iLLD/TC29B/Tricore/Eth/Std \
Libraries/iLLD/TC29B/Tricore/Fce/Crc \
Libraries/iLLD/TC29B/Tricore/Fce/Std \
Libraries/iLLD/TC29B/Tricore/Fft/Fft \
Libraries/iLLD/TC29B/Tricore/Fft/Std \
Libraries/iLLD/TC29B/Tricore/Flash/Std \
Libraries/iLLD/TC29B/Tricore/Gpt12/IncrEnc \
Libraries/iLLD/TC29B/Tricore/Gpt12/Std \
Libraries/iLLD/TC29B/Tricore/Gtm/Atom/Pwm \
Libraries/iLLD/TC29B/Tricore/Gtm/Atom/PwmHl \
Libraries/iLLD/TC29B/Tricore/Gtm/Atom/Timer \
Libraries/iLLD/TC29B/Tricore/Gtm/Std \
Libraries/iLLD/TC29B/Tricore/Gtm/Tim/In \
Libraries/iLLD/TC29B/Tricore/Gtm/Tom/Pwm \
Libraries/iLLD/TC29B/Tricore/Gtm/Tom/PwmHl \
Libraries/iLLD/TC29B/Tricore/Gtm/Tom/Timer \
Libraries/iLLD/TC29B/Tricore/Gtm/Trig \
Libraries/iLLD/TC29B/Tricore/Hssl/Hssl \
Libraries/iLLD/TC29B/Tricore/Hssl/Std \
Libraries/iLLD/TC29B/Tricore/I2c/I2c \
Libraries/iLLD/TC29B/Tricore/I2c/Std \
Libraries/iLLD/TC29B/Tricore/Iom/Driver \
Libraries/iLLD/TC29B/Tricore/Iom/Std \
Libraries/iLLD/TC29B/Tricore/Msc/Msc \
Libraries/iLLD/TC29B/Tricore/Msc/Std \
Libraries/iLLD/TC29B/Tricore/Mtu/Std \
Libraries/iLLD/TC29B/Tricore/Multican/Can \
Libraries/iLLD/TC29B/Tricore/Multican/Std \
Libraries/iLLD/TC29B/Tricore/Port/Io \
Libraries/iLLD/TC29B/Tricore/Port/Std \
Libraries/iLLD/TC29B/Tricore/Psi5/Psi5 \
Libraries/iLLD/TC29B/Tricore/Psi5/Std \
Libraries/iLLD/TC29B/Tricore/Psi5s/Psi5s \
Libraries/iLLD/TC29B/Tricore/Psi5s/Std \
Libraries/iLLD/TC29B/Tricore/Qspi/SpiMaster \
Libraries/iLLD/TC29B/Tricore/Qspi/SpiSlave \
Libraries/iLLD/TC29B/Tricore/Qspi/Std \
Libraries/iLLD/TC29B/Tricore/Scu/Std \
Libraries/iLLD/TC29B/Tricore/Sent/Sent \
Libraries/iLLD/TC29B/Tricore/Sent/Std \
Libraries/iLLD/TC29B/Tricore/Smu/Std \
Libraries/iLLD/TC29B/Tricore/Src/Std \
Libraries/iLLD/TC29B/Tricore/Stm/Std \
Libraries/iLLD/TC29B/Tricore/Stm/Timer \
Libraries/iLLD/TC29B/Tricore/Vadc/Adc \
Libraries/iLLD/TC29B/Tricore/Vadc/Std \
Libraries/iLLD/TC29B/Tricore/_Impl \
Libraries/iLLD/TC29B/Tricore/_Lib/DataHandling \
Libraries/iLLD/TC29B/Tricore/_Lib/InternalMux \
Libraries/iLLD/TC29B/Tricore/_PinMap \

