/**********************************************************************************************************************
 * \file CPU_Trap_Recognition.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "CPU_Trap_Recognition.h"
#include "Ifx_Types.h"
#include "Ifx_reg.h"
#include "IfxSmu.h"
#include "IfxMtu.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/ 
/* Set this macro to true to avoid the trap provocation and observe what steps are required to avoid the traps. */
#define AVOID_PROVOCATION           FALSE
/* Base address of the first MBIST (Memory Built In Self Test) Control Block */
#define IFXMTU_MC_ADDRESS_BASE      (0xF0061000u)
/* Select the DMA module for MBIST */
#define MBIST_REGISTER              IfxMtu_MbistSel_dma

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/* Different trap types are supported:
 *  - synchronous or asynchronous
 *  - hardware or software
 * Three different trap type combinations are supported and can be provoked by setting one of each variable to TRUE.
 */
uint16 g_provokeSynchronousHardwareTrap = FALSE;
uint16 g_provokeAsynchronousHardwareTrap = FALSE;
uint16 g_provokeSynchronousSoftwareTrap = FALSE;

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/* Depending on the values of the g_provokeXYTrap (X = Synchronous / Asynchronous; Y = Hardware / Software) global
 * variables, the following function provokes three different trap types if the AVOID_PROVOCATION is set to FALSE.
 */
void run_trap_provocation(void)
{
    if(g_provokeSynchronousHardwareTrap) /* The following code is based on the example MTU_MBIST_1 */
    {
        /* Get the pointer to Read Data and Bit Flip Register of specific MBIST module */
        Ifx_MTU_MC *mc = (Ifx_MTU_MC *)(IFXMTU_MC_ADDRESS_BASE + 0x100 * MBIST_REGISTER);

        #if AVOID_PROVOCATION
            IfxMtu_enableModule();                                                 /* Enable MTU clock               */
            IfxScuWdt_clearSafetyEndinit(IfxScuWdt_getSafetyWatchdogPassword());   /* Clear SafetyEndInit            */
            IfxMtu_enableMbistShell(MBIST_REGISTER);                               /* Enable MBIST Memory Controller */
        #endif

        /* Modify the register value. If the above steps are not done, it is causing a Data Access Synchronous Error */
        mc->RDBFL[0].U++;

        #if AVOID_PROVOCATION
            IfxScuWdt_setSafetyEndinit(IfxScuWdt_getSafetyWatchdogPassword());     /* Set SafetyEndInit              */
        #endif
    }
    else if(g_provokeAsynchronousHardwareTrap) /* The following code is based on the example SMU_IR_Alarm_1 */
    {
        #if AVOID_PROVOCATION
            /* Enable the SMU register configuration by setting the CFGLCK field of the SMU_KEYS register to 0xBC    */
            IfxSmu_unlockConfigRegisters();
            /* Clear SafetyEndInit protection for modification of the configuration registers                        */
            IfxScuWdt_clearSafetyEndinit(IfxScuWdt_getSafetyWatchdogPasswordInline());
        #endif

        /* Modify the register value. If the above steps are not done, it is causing a Data Access Asynchronous Error*/
        MODULE_SMU.AGC.B.IGCS0 = 1;

        #if AVOID_PROVOCATION
            /* Set SafetyEndInit protection after modification of the configuration registers                        */
            IfxScuWdt_setSafetyEndinit(IfxScuWdt_getSafetyWatchdogPasswordInline());
            /* After configuration, set a temporary lock of the SMU configuration                                    */
            IfxSmu_lockConfigRegisters();
        #endif
    }
    else if(g_provokeSynchronousSoftwareTrap)
    {
        Ifx_CPU_PSW psw;        /* Variable of the type PSW (Program Status Word, General Purpose Register)          */

        /* Get the content of the Program Status Word register with __mfcr instruction (Move From Core Register)     */
        psw.U   = __mfcr(CPU_PSW);
        psw.B.USB = 0x40;       /* Set the overflow bit in the PSV register                                          */

        #if AVOID_PROVOCATION
            psw.B.USB = 0x0;    /* Reset the overflow bit in the PSV register                                        */
        #endif

        __mtcr(CPU_PSW, psw.U); /* Write the modified register value with the __mtcr instruction                     */

        /* TRAPV instruction (trap on overflow) call, assembly instruction by using the __asm instruction.
         * If the overflow bit is set, an Arithmetic Overflow Trap will be triggered.
         */
        __asm("trapv");
    }
    else
    {
        /* Do nothing */
    }
}